language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin

before_script: pip instal docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"